### ISSUE TITLE
mostWordsEndWith.js should return an object and not a string

### ISSUE THREAD

**Issue by avermeulen** [Siyasanga/practical_objects#1]
@Siyasanga `mostWordsEndWith.js` currently return a string let it return an object in this format.

```javascript
{
   letter : 'the letter in question',
   letterCount : 10,
   
}```

/cc @Oyamashipula @Onwa2014

**Comment by Siyasanga** [comment]
@avermeulen i managed to get the function to return the result in this object format 
{ letter: 't', letterCount: 6 }
