### ISSUE TITLE
Please review mostProfitableDepartment

### ISSUE THREAD

**Issue by avermeulen** [Siyasanga/practical_objects#2]
@Siyasanga Please read the brief for mostProfitableDepartment.

# SHOP DEPARTMENTS

`A local shop want some help to determine which of their departments are the most profitable and which day of the week is the most profitable. Write two functions called mostProfitableDepartment, mostProfitableDay to help them to answer these questions.`

You need to find the department and day are the most profitable for all the days together. Let me know if I need to calrify thigns for you.

/cc @Oyamasiphula @Onwa2014

**Comment by Siyasanga** [comment]
@avermeulen hahaha my bad, i misunderstood the question, I'm on it. Thank you
